### ISSUE TITLE
手机加入网络后，微信语音通话功能无法正常使用

### ISSUE THREAD

**Issue by liquid207** [wi1dcard/kexue-gateway#2]
可以听到对方的声音，但是对方无法听到自己的声音。微信头像上有网络警告的红色小图标。

**Comment by wi1dcard** [comment]
如果你正在使用 Shadowsocks 协议，那么这里有个方案可以尝试一下：

拉取最新 Master 分支，再次运行 `./apply.sh`；相关 Commit：<https://github.com/wi1dcard/kexue-gateway/commit/7c45deac03d4028ef9d88ea6d7fd5ad1db22a7d1>。

该提交将路由配置中的 `domain_strategy` 修改为：

- 若 `dns_enabled` 为真，则 `domain_strategy` 为 `AsIs`。
- 若 `dns_enabled` 为假，则 `domain_strategy` 为 `IPOnDemand`。

而 `dns_enabled` 的值取决于 `forward_mode`：

<https://github.com/wi1dcard/kexue-gateway/blob/9872870a6e20f8d3f1df738a134ce831c0e7f247/defaults/advanced.yml#L42>

- 若 `forward_mode` 为 `vmess`，则 `dns_enabled` 为真。
- 其它情况，`dns_enabled` 为假。

因此，在本次提交之前，`domain_strategy` 被硬编码为 `AsIs`；而本次提交之后，如果你的 `forward_mode` 不是 `vmess`，那么 `domain_strategy` 默认将会被设置为 `IPOnDemand`。

根据 V2ray 文档：<https://www.v2ray.com/chapter_02/03_routing.html>，**使用 AsIs 将会导致路由规则内的 IP 规则失效**；又根据本项目的路由规则配置：

<https://github.com/wi1dcard/kexue-gateway/blob/9872870a6e20f8d3f1df738a134ce831c0e7f247/defaults/raw.yml#L37-L64>

以及 `dns_enabled` 为假时，默认启用 `sniffing_enabled`（文档参见 <https://www.v2ray.com/chapter_02/01_overview.html#sniffingobject>）：

<https://github.com/wi1dcard/kexue-gateway/blob/9872870a6e20f8d3f1df738a134ce831c0e7f247/defaults/advanced.yml#L44>

因此：如果 IP 规则失效将会导致，只有 HTTP 和 HTTPS 流量，且域名匹配 `geosite:cn`，才会走直连。其它流量全部都会走到代理。包括但不限于：

- 非 HTTP 和 HTTPS 流量（例如原生 TCP）
- 直接访问 IP 地址的 HTTP(S) 流量。
- ...

所以有可能导致你所描述的这个问题，而解决这个问题就需要将 `domain_strategy` 设置为 `IPOnDemand`，使路由配置内的 IP 规则生效。

------

那么为什么除 `vmess` 外，其它情况 `dns_enabled` 默认值均为 `false` 呢？

对于 VMess 协议，其传输层是基于 TCP 的。对于 DNS 请求这类 UDP 流量，是 UDP over TCP。也就是说不必担心 QoS 等因素引起的 UDP 丢包问题。

而对于 Shadowsocks 协议，其 UDP Relay 是同样依赖于 UDP 的。针对国内网络现状，UDP 流量很容易被网络运营商丢弃；所以必须根据你的网络情况、以及代理服务提供商的情况，测试 UDP 流量是否能够稳定传输，如果不稳定，那么 DNS 请求出现问题时，网络体验会很差。

而本项目并不提供代理服务，是无法保证链路稳定的；如果要求用户保证链路稳定难度太大，而且用户体验也不好。因此对于非 VMess 协议 `dns_enabled` 被默认设置为 `false`，通过 `sniffing_enabled` 和 `domain_strategy` 来「曲线救国」。

**Comment by wi1dcard** [comment]
当然，如果你能够确定你所在的网络环境到代理服务的 UDP 流量比较稳定的话，也可以尝试将 `dns_enabled` 设置为 `true`，带来更加 **接近原生** 的网络体验。
